//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Proejct.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public short Rate { get; set; }
        public int BookingBookingid { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
