//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Proejct.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5031_AssignmentContainer : DbContext
    {
        public FIT5031_AssignmentContainer()
            : base("name=FIT5031_AssignmentContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Booking> BookingSet { get; set; }
        public virtual DbSet<Courseinfo> CourseinfoSet { get; set; }
        public virtual DbSet<Feedback> FeedbackSet { get; set; }
    }
}
